# Configuration file

####################
# general
####################

general {
    S:version=1.0.1
}


####################
# item
####################

item {
    I:itemGateSettingsDuplicator.id=20513
    I:pipeItemsBounce.id=20508
    I:pipeItemsCrossover.id=20509
    I:pipeItemsExtraction.id=20507
    I:pipeItemsInsertion.id=20506
    I:pipeItemsRoundRobin.id=20505
    I:pipeItemsStripes.id=20500
    I:pipeLiquidsBalance.id=20503
    I:pipeLiquidsDiamond.id=20504
    I:pipeLiquidsGoldenIron.id=20502
    I:pipeLiquidsValve.id=20501
    I:pipePowerDiamond.id=20512
    I:pipePowerIron.id=20511
    I:pipePowerSwitch.id=20510
}


